DEGNet/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/urls.py
from django.conf.urls import url

from .views import *

app_name = 'main'

urlpatterns = [
    url('network_view', Network.as_view(), name='network_view'),
    url('deg_uploader', DEGUploader.as_view(), name='deg_uploader'),
    url('network_uploader', NetworkUploader.as_view(), name='network_uploader'),
    url('gene_conversion', GeneConversion.as_view(), name='gene_conversion'),
    url('anon_auth', anon_auth, name='anon_auth'),
    url('logout', logout_auth, name='logout'),
    url('login', Login.as_view(), name='login'),
    url('create_account', CreateAccount.as_view(), name='create_account'),
    url('api/get_network', get_network_json, name='get_network_api'),
    url('api/get_avail_network', get_avail_network_json, name='get_avail_network_api'),

    url('', Index.as_view(), name='index'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.views import View
from django.shortcuts import render

from .dir_views.index_view import *
from .dir_views.network_view import *
from .dir_views.deg_uploader import *
from .dir_views.network_uploader import *
from .dir_views.gene_conversion import *
from .dir_views.auth_util import *
from .dir_views.login_view import *
from .dir_views.create_account_view import *
from .dir_views.network_api import *

main/templates/main/base.html
{% extends "main/adminlte.html" %}
{% load static %}
{% with "main" as app %}


{% block main-header %}
<!-- Logo -->
<a href="#" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>D</b>Net</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>DEG</b>Net</span>
</a>

<nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
    </a>

    <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
            <!-- User Account: style can be found in dropdown.less -->
            <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <span class="hidden-xs">
                        {% if request.user.is_authenticated %}
                        <i class="fa fa-user"></i> {{ request.user.username }}
                        {% else %}
                        ---
                        {% endif %}
                    </span>
                </a>
                <ul class="dropdown-menu">
                    <!-- Menu Body -->
                    <li class="user-body">
                        <div class="row">
                            <div class="col-xs-6 text-center">
                                <a href="#">My Data</a>
                            </div>
                            <div class="col-xs-6 text-center">
                                <a href="#">My Account</a>
                            </div>
                        </div>
                        <!-- /.row -->
                    </li>
                    <!-- Menu Footer-->
                    <li class="user-footer">
                        <div class="pull-right">
                            <a href="{% url 'main:logout' %}" class="btn btn-default btn-flat">Sign out</a>
                        </div>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</nav>

{% endblock %}

{% block main-sidebar %}

<ul class="sidebar-menu" data-widget="tree">
    <li class="header">MAIN NAVIGATION</li>
    <li class="active">
        <a href="#">
            <i class="fa fa-align-justify"></i> <span>MAIN MENU</span>
        </a>
    </li>
    <li>
        <a href="{% url 'main:index' %}">
            <i class="fa fa-home"></i> <span>Home</span>
        </a>
    </li>
    <li class="treeview">
        <a href="#">
            <i class="fa fa-arrow-circle-right"></i> <span>Analysis</span>
        </a>
        <ul class="treeview-menu">
            <li>
                <a href="{% url 'main:deg_uploader' %}">
                    <i class="fa fa-circle-o {% if upload_data %}text-red{% endif %}"></i> Upload gene data
                </a>
            </li>
            <li>
                <a href="{% url 'main:network_uploader' %}">
                    <i class="fa fa-circle-o {% if upload_network %}text-red{% endif %}"></i> Upload new network
                </a>
            </li>
            <li>
                <a href="{% url 'main:network_view' %}">
                    <i class="fa fa-circle-o {% if network_view %}text-red{% endif %}"></i> View network
                </a>
            </li>
            <li><a href="pages/charts/flot.html"><i class="fa fa-circle-o"></i> Analyse Network</a></li>
        </ul>
    </li>
    <li class="treeview">
        <a href="pages/widgets.html">
            <i class="fa fa-wrench"></i> <span>Tools</span>
        </a>
        <ul class="treeview-menu">
            <li><a href="{% url 'main:gene_conversion' %}"><i
                    class="fa fa-circle-o {% if gene_id_conv %}text-red{% endif %}"></i> Gene ID conversion</a></li>
            <li><a href="pages/charts/morris.html"><i class="fa fa-circle-o"></i> Enrichment analysis</a></li>
        </ul>
    </li>
    <li class="treeview">
        <a href="pages/widgets.html">
            <i class="fa fa-database"></i> <span>Data</span>
        </a>
        <ul class="treeview-menu">
            <li><a href="pages/charts/chartjs.html"><i class="fa fa-circle-o"></i> Browse data</a></li>
            <li><a href="pages/charts/morris.html"><i class="fa fa-circle-o"></i> Download data</a></li>
        </ul>
    </li>
    <li>
        <a href="pages/widgets.html">
            <i class="fa fa-question-circle"></i> <span>Help</span>
        </a>
    </li>
    <li>
        <a href="pages/widgets.html">
            <i class="fa fa-info-circle"></i> <span>About</span>
        </a>
    </li>
    <li>
        <a href="pages/widgets.html">
            <i class="fa fa-envelope"></i> <span>Contact</span>
        </a>
    </li>
</ul>

{% endblock %}


{% endwith %}

main/templates/main/content.html
{% extends "main/base.html" %}
{% load static %}
{% with "main" as app %}

{% block content-wrapper %}
<section class="content-header">
    <h1>
        {{content_header}}
    </h1>
</section>
{% endblock %}

{% endwith %}

main/templates/main/create_account_form.html
<!DOCTYPE html>
{% load static %}
{% with "main" as app %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{{title}}{% endblock%}</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="shortcut icon" href="{% static '' %}{{app}}/icon/favicon.png" type="image/png">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{% static '' %}{{app}}/adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet"
          href="{% static '' %}{{app}}/adminlte/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{% static '' %}{{app}}/adminlte/bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static '' %}{{app}}/adminlte/dist/css/AdminLTE.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static '' %}{{app}}/adminlte/plugins/iCheck/square/blue.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{% static '' %}{{app}}/adminlte/dist/css/skins/_all-skins.min.css">
    <!-- Morris chart -->
    <link rel="stylesheet" href="{% static '' %}{{app}}/adminlte/bower_components/morris.js/morris.css">
    <!-- jvectormap -->
    <link rel="stylesheet" href="{% static '' %}{{app}}/adminlte/bower_components/jvectormap/jquery-jvectormap.css">
    <!-- Date Picker -->
    <link rel="stylesheet"
          href="{% static '' %}{{app}}/adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet"
          href="{% static '' %}{{app}}/adminlte/bower_components/bootstrap-daterangepicker/daterangepicker.css">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet"
          href="{% static '' %}{{app}}/adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
    {% block custom-css %}{% endblock %}
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>

<body class="hold-transition login-page">
<div class="login-box">
    {% if result == 'error' %}
    <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <h4><i class="icon fa fa-ban"></i> {{ result }}</h4>
        {{ message }}
    </div>
    {% elif result == 'success' %}
    <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <h4><i class="icon fa fa-check"></i> {{ result }}</h4>
        {{ message }} <a href="{% url 'main:login' %}">Login here</a>
    </div>
    {% endif %}
    <div class="login-logo">
        <a href="{% url 'main:index' %}"><b>DEG</b>Net</a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">Create you account</p>

        <form action="{% url 'main:create_account' %}" method="post">
            {% csrf_token %}
            <div class="form-group has-feedback">
                {{ form.username }}
                <span class="glyphicon glyphicon-user form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                {{ form.firstname }}
                <span class="glyphicon glyphicon-pencil form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                {{ form.lastname }}
                <span class="glyphicon glyphicon-pencil form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                {{ form.email }}
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                {{ form.password }}
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                {{ form.password2 }}
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="row">
                <div class="col-xs-offset-8 col-xs-4">
                    <button type="submit" class="btn btn-primary btn-block btn-flat">Register</button>
                </div>
                <!-- /.col -->
            </div>
        </form>
    </div>
    <!-- /.login-box-body -->
</div>
<!-- /.login-box -->


<!-- jQuery 3 -->
<script src="{% static '' %}{{app}}/adminlte/bower_components/jquery/dist/jquery.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static '' %}{{app}}/adminlte/bower_components/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);



</script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static '' %}{{app}}/adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- Morris.js charts -->
<script src="{% static '' %}{{app}}/adminlte/bower_components/raphael/raphael.min.js"></script>
<script src="{% static '' %}{{app}}/adminlte/bower_components/morris.js/morris.min.js"></script>
<!-- Sparkline -->
<script src="{% static '' %}{{app}}/adminlte/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
<!-- jvectormap -->
<script src="{% static '' %}{{app}}/adminlte/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
<script src="{% static '' %}{{app}}/adminlte/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<!-- jQuery Knob Chart -->
<script src="{% static '' %}{{app}}/adminlte/bower_components/jquery-knob/dist/jquery.knob.min.js"></script>
<!-- daterangepicker -->
<script src="{% static '' %}{{app}}/adminlte/bower_components/moment/min/moment.min.js"></script>
<script src="{% static '' %}{{app}}/adminlte/bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>
<!-- datepicker -->
<script src="{% static '' %}{{app}}/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{% static '' %}{{app}}/adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
<!-- Slimscroll -->
<script src="{% static '' %}{{app}}/adminlte/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<!-- FastClick -->
<script src="{% static '' %}{{app}}/adminlte/bower_components/fastclick/lib/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="{% static '' %}{{app}}/adminlte/dist/js/adminlte.min.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static '' %}{{app}}/adminlte/dist/js/pages/dashboard.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static '' %}{{app}}/adminlte/dist/js/demo.js"></script>
<script src="{% static '' %}{{app}}/adminlte/plugins/iCheck/icheck.min.js"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' // optional
    });
  });


</script>
</body>
</html>
{% endwith %}

main/templates/main/index.html
{% extends "main/content.html" %}
{% load static %}
{% with "main" as app %}

{% block content-wrapper %}
{{ block.super }}

<section class="content">

</section>

{% if not is_auth %}
<div class="modal show" id="modal-default">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="info-box">
                            <span class="info-box-icon bg-green"><i class="fa fa-user"></i></span>

                            <div class="info-box-content">
                                <span class="info-box-text"><b>Anonymous</b></span>
                                <p class="info-box-text">Start using this web anonymously</p>
                                <a href="{% url 'main:anon_auth' %}" class="btn btn-primary btn-sm"><i class="fa fa-play "></i> Start as anonymous</a>
                            </div>
                            <!-- /.info-box-content -->
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="info-box">
                            <span class="info-box-icon bg-green"><i class="fa fa-key"></i></span>

                            <div class="info-box-content">
                                <span class="info-box-text"><b>Login</b></span>
                                <p class="info-box-text">Go to login page.</p>
                                <a id="login" href="{% url 'main:login' %}" class="btn btn-primary btn-sm"><i class="fa fa-play "></i> Login page</a>
                            </div>
                            <!-- /.info-box-content -->
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="info-box">
                            <span class="info-box-icon bg-green"><i class="fa fa-user-plus"></i></span>

                            <div class="info-box-content">
                                <span class="info-box-text"><b>Create new account</b></span>
                                <p class="info-box-text">Go to create account page.</p>
                                <a href="{% url 'main:create_account' %}" class="btn btn-primary btn-sm"><i class="fa fa-play "></i> Create account</a>
                            </div>
                            <!-- /.info-box-content -->
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->
{% endif %}

{% endblock %}

{% endwith %}

main/templates/main/login_form.html
<!DOCTYPE html>
{% load static %}
{% with "main" as app %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{{title}}{% endblock%}</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="shortcut icon" href="{% static '' %}{{app}}/icon/favicon.png" type="image/png">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{% static '' %}{{app}}/adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet"
          href="{% static '' %}{{app}}/adminlte/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{% static '' %}{{app}}/adminlte/bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static '' %}{{app}}/adminlte/dist/css/AdminLTE.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static '' %}{{app}}/adminlte/plugins/iCheck/square/blue.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{% static '' %}{{app}}/adminlte/dist/css/skins/_all-skins.min.css">
    <!-- Morris chart -->
    <link rel="stylesheet" href="{% static '' %}{{app}}/adminlte/bower_components/morris.js/morris.css">
    <!-- jvectormap -->
    <link rel="stylesheet" href="{% static '' %}{{app}}/adminlte/bower_components/jvectormap/jquery-jvectormap.css">
    <!-- Date Picker -->
    <link rel="stylesheet"
          href="{% static '' %}{{app}}/adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet"
          href="{% static '' %}{{app}}/adminlte/bower_components/bootstrap-daterangepicker/daterangepicker.css">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet"
          href="{% static '' %}{{app}}/adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
    {% block custom-css %}{% endblock %}
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>

<body class="hold-transition login-page">
<div class="login-box">
    {% if result == 'error' %}
    <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <h4><i class="icon fa fa-ban"></i> {{ result }}</h4>
        {{ message }}
    </div>
    {% endif %}
    <div class="login-logo">
        <a href="{% url 'main:index' %}"><b>DEG</b>Net</a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>

        <form action="{% url 'main:login' %}" method="post">
            {% csrf_token %}
            <div class="form-group has-feedback">
                {{ form.username }}
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                {{ form.password }}
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="row">
                <!--<div class="col-xs-8">-->
                    <!--<div class="checkbox icheck">-->
                        <!--<label>-->
                            <!--<input type="checkbox"> Remember Me-->
                        <!--</label>-->
                    <!--</div>-->
                <!--</div>-->
                <!-- /.col -->
                <div class="col-xs-8-offset col-xs-4">
                    <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
                </div>
                <!-- /.col -->
            </div>
        </form>

        <a href="#">I forgot my password</a><br>
        <a href="{% url 'main:create_account' %}" class="text-center">Register a new membership</a>

    </div>
    <!-- /.login-box-body -->
</div>
<!-- /.login-box -->


<!-- jQuery 3 -->
<script src="{% static '' %}{{app}}/adminlte/bower_components/jquery/dist/jquery.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static '' %}{{app}}/adminlte/bower_components/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);

</script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static '' %}{{app}}/adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- Morris.js charts -->
<script src="{% static '' %}{{app}}/adminlte/bower_components/raphael/raphael.min.js"></script>
<script src="{% static '' %}{{app}}/adminlte/bower_components/morris.js/morris.min.js"></script>
<!-- Sparkline -->
<script src="{% static '' %}{{app}}/adminlte/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
<!-- jvectormap -->
<script src="{% static '' %}{{app}}/adminlte/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
<script src="{% static '' %}{{app}}/adminlte/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<!-- jQuery Knob Chart -->
<script src="{% static '' %}{{app}}/adminlte/bower_components/jquery-knob/dist/jquery.knob.min.js"></script>
<!-- daterangepicker -->
<script src="{% static '' %}{{app}}/adminlte/bower_components/moment/min/moment.min.js"></script>
<script src="{% static '' %}{{app}}/adminlte/bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>
<!-- datepicker -->
<script src="{% static '' %}{{app}}/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{% static '' %}{{app}}/adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
<!-- Slimscroll -->
<script src="{% static '' %}{{app}}/adminlte/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<!-- FastClick -->
<script src="{% static '' %}{{app}}/adminlte/bower_components/fastclick/lib/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="{% static '' %}{{app}}/adminlte/dist/js/adminlte.min.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static '' %}{{app}}/adminlte/dist/js/pages/dashboard.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static '' %}{{app}}/adminlte/dist/js/demo.js"></script>
<script src="{% static '' %}{{app}}/adminlte/plugins/iCheck/icheck.min.js"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' // optional
    });
  });
</script>
</body>
</html>
{% endwith %}

main/templates/main/main.html
{% extends "main/content.html" %}
{% load static %}
{% with "main" as app %}

{% block content-wrapper %}
{{ block.super }}

<section class="content">

</section>

{% if not is_auth %}
<div class="modal show" id="modal-default">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="info-box">
                            <span class="info-box-icon bg-green"><i class="fa fa-user"></i></span>

                            <div class="info-box-content">
                                <span class="info-box-text"><b>Anonymous</b></span>
                                <p class="info-box-text">Start using this web anonymously</p>
                                <button id="anon" type="button" class="btn btn-primary btn-sm"><i class="fa fa-play "></i> Start</button>
                            </div>
                            <!-- /.info-box-content -->
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="info-box">
                            <span class="info-box-icon bg-green"><i class="fa fa-key"></i></span>

                            <div class="info-box-content">
                                <span class="info-box-text"><b>Login</b></span>
                                <p class="info-box-text">Go to login page.</p>
                                <a id="login" href="{% url 'main:login' %}" class="btn btn-primary btn-sm"><i class="fa fa-play "></i> Login page</a>
                            </div>
                            <!-- /.info-box-content -->
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="info-box">
                            <span class="info-box-icon bg-green"><i class="fa fa-user-plus"></i></span>

                            <div class="info-box-content">
                                <span class="info-box-text"><b>Create new account</b></span>
                                <p class="info-box-text">Go to create account page.</p>
                                <a href="{% url 'main:create_account' %}" class="btn btn-primary btn-sm"><i class="fa fa-play "></i> Create account</a>
                            </div>
                            <!-- /.info-box-content -->
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->
{% endif %}

{% endblock %}

{% endwith %}